PREFIX cl: <https://w3id.org/sepses/vocab/log/core#>
PREFIX au: <https://w3id.org/sepses/vocab/log/audit#>
SELECT * 
WHERE {
   ?s   cl:timestamp   ?t. ?s   au:type     ?ty. ?s   au:arch     ?arc.   
   ?s   au:syscall  ?sys. ?s   au:success  ?suc.   ?s   au:exit  ?exi.
   ?s   au:a0     ?a0.   ?s   au:a1     ?a1. ?s   au:a2  ?a2.   
   ?s   au:a3  ?a3. ?s   au:items  ?it.   ?s   au:ppid     ?ppi.
   ?s   au:pid     ?pi.   ?s   au:auid  ?aui. ?s   au:gid  ?gi.
   ?s   au:euid     ?eui.   ?s   au:suid     ?sui. ?s   au:fsuid  ?fsui.
   #?s   au:egid  ?egi. ?s   au:fsgid     ?fsgi. 
   ?s   au:tty     ?tt. 
   ?s   au:exe  ?ex.
   #?s   au:sgid  ?sgid. 
   #?s   au:ses  ?se.
   #?s   au:comm  ?co. 
   #?s   au:uid  ?ui.   

} LIMIT 1


