PREFIX cl: <https://w3id.org/sepses/vocab/log/coreLog#>
PREFIX auth: <https://w3id.org/sepses/vocab/log/authLog#>
SELECT ?s ?timestamp ?message ?program  WHERE {
 ?s   cl:message   ?message.
 ?s   auth:programName   ?program.
 ?s   cl:timestamp   ?timestamp.		
}