PREFIX cl: <https://w3id.org/sepses/vocab/log/core#>
PREFIX auth: <https://w3id.org/sepses/vocab/log/auth#>
SELECT *
WHERE {
 ?s   cl:message   ?message.
 ?s   cl:timestamp   ?timestamp.
 ?s   auth:pid   ?pid.	
 ?s   auth:hasProgram   ?program.	
 ?s   auth:hasTargetHost   ?targetHost.	
 #?s   auth:hasUser   ?user.	
 #?s   auth:hasSourceIp   ?sourceIp.		
 #?s   auth:hasSourcePort   ?sourcePort.		
 #?s   auth:hasAuthEvent   ?authEvent.		
 #?s   cl:hostName   ?hostName.		
 #?s   cl:hasLogFamily ?logfamily.
#FILTER regex(str(?message),'root')
}
LIMIT 100