PREFIX cl: <https://w3id.org/sepses/vocab/log/coreLog#>
PREFIX apache: <https://w3id.org/sepses/vocab/log/apacheLog#>
SELECT ?s ?timestamp ?clientip ?verb ?request WHERE {
 ?s   apache:hasClient   ?clientip.
 ?s   apache:hasRequestVerb   ?verb.
 ?s   apache:hasRequest   ?request.
 ?s   cl:timestamp   ?timestamp.
FILTER regex(?verb,'GET')
FILTER regex(?request,'php')
FILTER regex(?clientip,'10.2.21.173')
	}			
	LIMIT 50