PREFIX cl: <https://w3id.org/sepses/vocab/log/coreLog#>
PREFIX sa: <https://w3id.org/sepses/vocab/log/snort-alert#>
PREFIX sr: <http://w3id.org/sepses/vocab/rule/snortRule#>
PREFIX cve: <http://w3id.org/sepses/vocab/ref/cve#>
PREFIX cvss: <http://w3id.org/sepses/vocab/ref/cvss#>

SELECT ?s ?timestamp ?message ?sid ?cve ?score WHERE {
 ?s   cl:timestamp   ?timestamp.
 ?s   cl:message   ?message.
 ?s   sa:signatureId ?sid.
 ?sid  sr:hasRuleOption ?ro.
 ?ro sr:hasCVEReference ?cve.
 ?cve cve:hasCVSS2BaseMetric ?cbm.
?cbm cvss:baseScore ?score.
FILTER regex(?message,'WEB-MISC Netscape Enterprise')
#FILTER regex(?message,'ICMP Destination Unreachable')
#FILTER regex(?message,'WEB-MISC Chunked-Encoding')
#FILTER regex(?message,'WEB-MISC WebDAV search')
#FILTER regex(?message,'WEB-MISC TRACE attempt')
#FILTER regex(?message,'WEB-FRONTPAGE rad fp30reg.dll')
 
	 
}			
LIMIT 3
	 