PREFIX cl: <https://w3id.org/sepses/vocab/log/coreLog#>
PREFIX auth: <https://w3id.org/sepses/vocab/log/authLog#>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
	
SELECT ?s ?timestamp ?program ?message ?logfamily ?abst WHERE {
  ?s   cl:message   ?message.
  ?s   cl:timestamp   ?timestamp.
  ?s   auth:programName   ?program.
  ?s   cl:hasLogFamily  ?lf.
  ?lf  rdfs:label  ?logfamily.
  ?lf  dbo:abstract ?abst.		
FILTER regex(?message,'Received')
}
LIMIT 50